INCLUDES += -I$(PKGDIRBASE)/lvgl

CFLAGS += -Wno-pedantic -Wno-unused-parameter -Wno-sign-compare -Wno-cast-function-type

CFLAGS += -DLV_CONF_INCLUDE_SIMPLE -DLV_LVGL_H_INCLUDE_SIMPLE

ifneq (,$(filter lvgl_sdl,$(USEMODULE)))
  INCLUDES += -I$(PKGDIRBASE)/lvgl-sdl
  LINKFLAGS += $(shell sdl2-config --libs)
  DIRS += $(RIOTBASE)/pkg/lvgl/sdl
endif
