PKG_NAME=lvgl-sdl
PKG_URL=https://github.com/j-devel/RIOT-pkg-lvgl-sdl
PKG_VERSION=be415fe37eaeec8cb0602509ec7ec08ced7135a1
PKG_LICENSE=MIT

include $(RIOTBASE)/pkg/pkg.mk

all:
	@echo building lvgl-sdl
	make -C $(PKG_BUILDDIR)
